apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "gogs.fullname" . }}
  labels:
    app: {{ template "gogs.name" . }}
    chart: {{ template "gogs.chart" . }} 
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "gogs.name" . }}
      chart: {{ template "gogs.chart" . }} 
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance }}
  template:
    metadata:
      labels:
        app: {{ template "gogs.name" . }}
        chart: {{ template "gogs.chart" . }} 
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "gogs/gogs:0.11.29"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
            - containerPort: 22
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          env:
            # https://github.com/gogits/gogs/tree/master/docker#container-options
            - name: SOCAT_LINK
              value: "false"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /data/gogs/conf/app.ini
              subPath: app.ini
      volumes:
        - name: config
          configMap:
            name: {{ template "gogs.fullname" . }}-config
        - name: data
      {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "gogs.fullname" . }}
      {{- else }}
          emptyDir: {}
      {{- end -}}
