apiVersion: v1
kind: Service
metadata:
  name: {{ template "rucio.fullname" . }}-auth
  labels:
    app: {{ template "rucio.name" . }}-auth
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.authServer.servicePort }}
      targetPort: {{ $.Values.authServer.targetPort }}
      protocol: TCP
      name: {{ $.Values.authServer.portName }}
  selector:
    app: {{ template "rucio.name" . }}-auth
    release: {{ .Release.Name }}
