apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "rucio.fullname" . }}-auth
  labels:
    app: {{ template "rucio.name" . }}-auth
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.authReplicaCount }}
  selector:
    matchLabels:
      app: {{ template "rucio.name" . }}-auth
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml . | trim | indent 6 }}
    {{- end }}
{{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ template "rucio.name" . }}-auth
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: aliases
        configMap:
          name: {{ template "rucio.fullname" . }}-auth-aliases
      - name: httpdlog
        emptyDir: {}
{{- if .Values.authServer.useSSL }}
      - name: hostcert
        secret:
          secretName: {{ .Values.SecretNames.hostcert }} 
      - name: hostkey
        secret:
          secretName: {{ .Values.SecretNames.hostkey }}
      - name: cafile
        secret:
          secretName: {{ .Values.SecretNames.cafile }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}-auth
          image: "rucio/rucio-server:release-1.18.0"
          imagePullPolicy: Always 
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: httpdlog
              mountPath: /var/log/httpd
            - name: aliases
              mountPath: /opt/rucio/etc/aliases.conf
              subPath: aliases.conf
{{- if .Values.authServer.useSSL }}
            - name: hostcert
              mountPath: /etc/grid-security/hostcert.pem
              subPath: hostcert.pem
            - name: hostkey
              mountPath: /etc/grid-security/hostkey.pem
              subPath: hostkey.pem
            - name: cafile
              mountPath: /etc/grid-security/ca.pem
              subPath: ca.pem
{{- end }}
          env:
            {{- range $key1, $val1 := .Values.config }}
            {{- range $key2, $val2 := $val1}}
            - name: RUCIO_CFG_{{ $key1 | upper }}_{{ $key2 | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "rucio.fullname" $ }}.cfg
                  key: {{ $key1 }}_{{ $key2 }}
            {{- end}}
            {{- end}}
{{- if .Values.authServer.useSSL }}
            - name: RUCIO_ENABLE_SSL
              value: "True"
            - name: OPENSSL_ALLOW_PROXY_CERTS
              value: "1"
{{- else }}
            - name: RUCIO_ENABLE_SSL
              value: "False"
{{- end }}
            - name: RUCIO_DEFINE_ALIASES
              value: "True"
            - name: RUCIO_LOG_FORMAT
              value: '[%{%Y-%m-%d %H:%M:%S}t]\t%v\t%h\t%{X-Forwarded-For}i\t%{X-Rucio-RequestId}i\t%>s\t%I\t%B\t%D\t\"%r\"\t\"%{X-Rucio-Auth-Token}i\"\t\"%{User-Agent}i\"\t%{X-Rucio-Script}i'
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
