apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nextflow-api.fullname" . }}
  labels:
    app: {{ template "nextflow-api.name" . }}
    chart: {{ template "nextflow-api.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  replicas: {{ .Values.Replicas }}
  selector:
    matchLabels:
      app: {{ template "nextflow-api.name" . }}
      instance: {{ .Values.Instance }}
  template:
    metadata:
      labels:
        app: {{ template "nextflow-api.name" . }}
        chart: {{ template "nextflow-api.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      serviceAccountName: nextflow-api-auth-svc
      containers:
      - name: nextflow-server
        image: cbmckni/nextflow-api
        env:
        - name: NEXTFLOW_K8S
          value: "true"
        command:
        - /bin/bash
        - -c
        - cd /opt/nextflow-api; cp -R /etc/.kube /root; kubectl config --kubeconfig=/root/.kube/config use-context {{ .Values.Remote.Context }}; kubectl get pods; python3 server.py
        resources:
          requests:
            cpu: {{ .Values.Resources.CPU }}
            memory: {{ .Values.Resources.Memory }}
        volumeMounts:
        - name: vol-1
          mountPath: /workspace
        - name: conf
          mountPath: "/etc/.kube"
        ports:
        - containerPort: 8080
      volumes:
      - name: vol-1
        persistentVolumeClaim:
          claimName: {{ .Values.PersistentVolumeClaim.Name }}
      - name: conf
        secret:
          secretName: kubeconfig
          defaultMode: 256
