kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.PersistentVolumeClaim.Name }}
  labels:
    app: {{ template "nextflow-api.name" . }}
    chart: {{ template "nextflow-api.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.PersistentVolumeClaim.StorageClass }}
  resources:
    requests:
      storage: {{ .Values.PersistentVolumeClaim.Size }}
