apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osg-frontier-squid.fullname" . }}
  labels:
    app: {{ template "osg-frontier-squid.name" . }}
    chart: {{ template "osg-frontier-squid.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osg-frontier-squid.name" . }}
      chart: {{ template "osg-frontier-squid.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance }}

  template:
    metadata:
      labels:
        app: {{ template "osg-frontier-squid.name" . }}
        chart: {{ template "osg-frontier-squid.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      # Required affinity for using local storage
      {{ if .Values.SLATE.LocalStorage }}
      nodeSelector:
        storage: "local"
      {{ end }}
      containers:
      # Container for the primary application, OSG Frontier Squid
      - name: osg-frontier-squid
        image: opensciencegrid/frontier-squid:development
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            ephemeral-storage: "1Gi"
          limits:
            ephemeral-storage: "5Gi"
        ports:
        - containerPort: 3128
          name: squid
        env:
        - name: SQUID_IPRANGE
          value: "{{ .Values.SquidConf.IPRange }}"
        - name: SQUID_CACHE_DISK
          value: "{{ .Values.SquidConf.CacheSize }}"
        - name: SQUID_CACHE_MEM
          value: "{{ .Values.SquidConf.CacheMem }}"
        volumeMounts:
        # Storage location of the cache data
        - mountPath: /var/cache/squid/osg-frontier-squid-{{ .Values.Instance }}-cache
          subPath: osg-frontier-squid-{{ .Values.Instance }}-cache
          name: osg-frontier-squid-{{ .Values.Instance }}-data
          # Shared directory for logs with the Fluent-bit sidecar, can be enabled or disabled from values.yaml
        {{ if .Values.SLATE.Logging.Enabled }}
        - mountPath: /var/log/squid
          name: varlog
        # Container for fluent-bit logging sidecar. Enabled/disabled within values.yaml
      - name: fluent-bit
        image: fluent/fluent-bit:1.0.6
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
        volumeMounts:
          # Configuration file for fluent-bit sidecar
        - name: {{ template "osg-frontier-squid.fullname" . }}-fluent-bit-config
          mountPath: /fluent-bit/etc/
          # Shared directory for logging from application
        - name: varlog
          mountPath: /var/log/squid
          {{ end }}
      volumes:
        - name: osg-frontier-squid-{{ .Values.Instance }}-data
        {{ if .Values.SLATE.LocalStorage }}
          persistentVolumeClaim:
            claimName: osg-frontier-squid-{{ .Values.Instance }}-pvc
        {{ else }}
          emptyDir: {}
        {{ end }}

        {{ if .Values.SLATE.Logging.Enabled }}
        # Volumes required by fluent-bit sidecar for configuration and accessing application logs of frontier-squid
        - name: {{ template "osg-frontier-squid.fullname" . }}-fluent-bit-config
          configMap:
            name: {{ template "osg-frontier-squid.fullname" . }}-fluent-bit-config
        - name: varlog
          emptyDir: {}
        {{ end }}
