apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-sql-test-{{ randAlphaNum 5 | lower }}"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: {{ .Release.Name }}-sql-test
      image: "k8s.gcr.io/spark:1.5.1_v3"
      command: ["{{ .Values.Spark.Path }}/bin/spark-sql", "--master",
                "spark://{{ .Release.Name }}-master:{{ .Values.Master.ServicePort }}", "-e",
                "show databases;"]
  restartPolicy: Never
