apiVersion: v1
kind: Service
metadata:
  name: {{ template "condor-ce.fullname" . }}-ssh
  labels:
    app: {{ template "condor-ce.fullname" . }}
    chart: {{ template "condor-ce.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  type: NodePort
  ports:
  - name: ssh
    targetPort: ssh
    port: 22
    protocol: TCP
  - name: collector
    targetPort: collector
    port: 9619
    protocol: TCP
  selector:
    app: {{ template "condor-ce.fullname" . }}
    instance: {{ .Values.Instance }}
release: {{ .Release.Name }}