{{ if and .Values.AuthMethod (eq .Values.AuthMethod "token") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "condor-login.fullname" . }}-token-config
  labels: 
    app: {{ template "condor-login.fullname" . }}
    chart: {{ template "condor-login.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
data:
  90-token.conf: |
    SEC_DEFAULT_AUTHENTICATION_METHODS = TOKEN,FS
    SEC_CLIENT_AUTHENTICATION_METHODS = TOKEN,FS
{{ end }}
---
{{ if .Values.CentralManager }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "condor-login.fullname" . }}-schedd-config
  labels: 
    app: {{ template "condor-login.fullname" . }}
    chart: {{ template "condor-login.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
data:
  99-schedd.conf: |+
    DAMEON_LIST = MASTER, SCHEDD
    CONDOR_HOST = {{ .Values.CentralManager }}
    #CCB_ADDRESS = {{ .Values.CentralManager }}
    USE_SHARED_PORT = true
    # undefine
    FLOCK_TO =  
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "condor-login.fullname" . }}-config
  labels: 
    app: {{ template "condor-login.fullname" . }}
    chart: {{ template "condor-login.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
data:
  tconfig-file.conf: |+
{{ .Values.LoginConfigFile | indent 4 }}
