apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "condor-login.fullname" . }}-config-osg
  labels:
    app: {{ template "condor-login.fullname" . }}
    chart: {{ template "condor-login.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cvmfs-config-osg
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "condor-login.fullname" . }}-connect
  labels:
    app: {{ template "condor-login.fullname" . }}
    chart: {{ template "condor-login.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cvmfs-connect
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "condor-login.fullname" . }}-oasis
  labels:
    app: {{ template "condor-login.fullname" . }}
    chart: {{ template "condor-login.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cvmfs-oasis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "condor-login.fullname" . }}-spt
  labels:
    app: {{ template "condor-login.fullname" . }}
    chart: {{ template "condor-login.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cvmfs-spt
