apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "slate-api.fullname" . }}
  labels:
    app: {{ template "slate-api.fullname" . }}
    chart: {{ template "slate-api.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  replicas: {{ .Values.Replicas }}
  selector:
    matchLabels:
      app: {{ template "slate-api.fullname" . }}
      chart: {{ template "slate-api.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance }}
  template:
    metadata:
      labels: 
        app: {{ template "slate-api.fullname" . }}
        chart: {{ template "slate-api.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      containers:
      - name: slate-api
        image: "slateci/container-slate-api"
        imagePullPolicy: IfNotPresent
        ports:
        - name: rest
          containerPort: 18080
          protocol: TCP
        env:
          - name: SLATE_awsRegion
            value: {{ .Values.PesistentStore.AWSRegion | quote }}
          - name: SLATE_awsURLScheme
            value: {{ .Values.PesistentStore.AWSURLScheme | quote }}
          - name: SLATE_awsEndpoint
            value: {{ .Values.PesistentStore.AWSEndpoint | quote }}
          - name: SLATE_appLoggingServerName
            value: {{ .Values.Logging.ServerName | quote }}
          - name: SLATE_appLoggingServerPort
            value: {{ .Values.Logging.ServerPort | quote }}
          - name: SLATE_awsAccessKey
            valueFrom:
              secretKeyRef:
                name: {{ .Values.SecretName }}
                key: awsAccessKey
          - name: SLATE_awsSecretKey
            valueFrom:
              secretKeyRef:
                name: {{ .Values.SecretName }}
                key: awsSecretKey
          - name: SLATE_encryptionKeyFile
            value: "conf/encryptionKey"
          {{ if .Values.TLSSecretName }}
          - name: SLATE_sslCertificate
            value: "tlsConf/sslCertificate"
          - name: SLATE_sslKey
            value: "tlsConf/sslKey"
          {{ end }}
        volumeMounts:
          - name: encryption-key
            mountPath: "/opt/slate-api-server/conf"
          {{ if .Values.TLSSecretName }}
          - name: ssl-certificate
            mountPath: "/opt/slate-api-server/tlsConf"
          {{ end }}
      volumes:
      - name: encryption-key
        secret:
          secretName: {{ .Values.SecretName }}
          items:
          - key: encryptionKey
            path: encryptionKey
      {{ if .Values.TLSSecretName }}
      - name: ssl-certificate
        secret:
          secretName: {{ .Values.TLSSecretName }}
      {{ end }}
